name: gamebe
description: Graduation Project


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  #design
  introduction_screen: ^2.1.0
  animated_text_kit: ^4.2.1
  animated_bottom_navigation_bar: ^0.3.2
  curved_navigation_bar: ^1.0.2
  flutter_login: ^3.1.0
  flutter_signin_button: ^2.0.0

  #firebase_links:
  cloud_firestore: ^3.1.6
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.6
  flutter_settings_screens: ^0.3.2-null-safety

  #sign_in
  google_sign_in: ^5.2.3


  flutter_test:

    sdk: flutter



  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true
  assets:
    - images/
  fonts:
  - family: AlfaSlabOne
    fonts:
    - asset: fonts/AlfaSlabOne-Regular.ttf


